version: "3.8"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - PLEX_CLAIM=${PLEX_CLAIM_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    ports:
      - "32400:32400"
    runtime: nvidia
    privileged: true
    volumes:
      - ${MEDIADIR}/config/plexdata/config:/config
      - ${MEDIADIR}/config/transcode:/transcode
      - ${MEDIADIR}/media/movies:/movies
      - ${MEDIADIR}/media/TV:/TV
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIADIR}/config/radarr:/config
      - ${MEDIADIR}:/data
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIADIR}/config/sonarr:/config
      - ${MEDIADIR}:/data
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${MEDIADIR}/config/bazarr:/config
      - ${MEDIADIR}/media:/data/media
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    security_opt:
      - no-new-privileges:true
    ports:
      - "8089:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIADIR}/config/sabnzbd:/config
      - ${MEDIADIR}/usenet:/data/usenet:rw
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=911
      - PGID=911
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIADIR}/config/organizr:/config
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${MEDIADIR}/config/overseerr:/config
    ports:
      - "5055:5055"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    security_opt:
      - no-new-privileges:true
    ports:
      - "8181:8181"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIADIR}/config/tautulli:/config
      - "${MEDIADIR}/config/plexdata/config/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${MEDIADIR}/config/prowlarr:/config
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UN_LOG_FILE=/downloads/unpackerr.log
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_SONARR_0_PATHS_0=/data/downloads
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
      - UN_RADARR_0_PATHS_0=/data/downloads
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${MEDIADIR}:/data
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    security_opt:
      - no-new-privileges:true
    ports:
      - "8191:8191"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESS}
      - WIREGUARD_DNS=auto
      - SERVER_COUNTRIES=Netherlands
      - FIREWALL=on
      - DNS=none
      - DOT=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port.json
      - PORT_FORWARDING_STATUS_FILE_FORMAT=json
    volumes:
      - ${MEDIADIR}/gluetun:/gluetun
    ports:
      - "127.0.0.1:8080:8080"
      - "8001:8000/tcp"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "container:gluetun"
    depends_on:
      - gluetun
    volumes:
      - ${MEDIADIR}/config/qbittorrent:/config
      - ${MEDIADIR}:/data
      - ${MEDIADIR}/gluetun:/gluetun
    environment:
      - WEBUI_PORT=8080
      - QBITTORRENT_PORT_FORWARDING=yes
      - GLUETUN_PORT_FORWARD_STATUS_FILE=/tmp/gluetun/forwarded_port.json
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  gluetun-qbittorrent-port-manager:
    image: snoringdragon/gluetun-qbittorrent-port-manager:latest
    container_name: port-manager
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
      - qbittorrent
    volumes:
      - ${MEDIADIR}/gluetun:/tmp/gluetun:ro
    environment:
      - QBITTORRENT_SERVER=localhost
      - QBITTORRENT_PORT=8080
      - QBITTORRENT_USER=admin
      - QBITTORRENT_PASS=${qbittorrent_pass}
      - PORT_FORWARDED=/tmp/gluetun/forwarded_port.json
      - HTTP_S=http
      - GLUETUN_HOST=localhost
      - GLUETUN_PORT=8000
      - RECHECK_TIME=60
      - TZ=America/Chicago
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6
    container_name: cross-seed
    user: 911:911
    networks:
      - proxy
    volumes:
      - ${MEDIADIR}/config/cross-seed:/config
      - ${MEDIADIR}:/data
    command: daemon
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    restart: unless-stopped
    hostname: notifiarr
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DN_API_KEY=${NOTIFIARR_API_KEY}
      - TZ=America/Chicago
    volumes:
      - ${MEDIADIR}/config/notifiarr:/config
      - /:/host:ro,rslave
    ports:
      - "5454:5454"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:latest
    container_name: dispatcharr
    networks:
      - proxy
    ports:
      - "9191:9191"
    volumes:
      - ${MEDIADIR}/config/TV:/data
    environment:
      - DISPATCHARR_ENV=aio
      - DISPATCHARR_TUNER_MODE=hdhomerun
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable --schedule "0 0 4 * * *"
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run overseerr-tunnel
    networks:
      - proxy
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"

networks:
  proxy:
    driver: bridge
